### ISSUE TITLE
WebDriverRunner.getBrowserDownloadsFolder() returns null

### ISSUE THREAD

**Issue by mszajowskiwr** [selenide/selenide-selenoid#3]
With the following diff, the test fails:

```diff
diff --git a/src/test/java/org/selenide/examples/selenoid/FileDownloadTest.java b/src/test/java/org/selenide/examples/selenoid/FileDownloadTest.java
index c2e0969..63b8943 100644
--- a/src/test/java/org/selenide/examples/selenoid/FileDownloadTest.java
+++ b/src/test/java/org/selenide/examples/selenoid/FileDownloadTest.java
@@ -2,6 +2,7 @@ package org.selenide.examples.selenoid;
 
 import com.codeborne.selenide.Configuration;
 import com.codeborne.selenide.FileDownloadMode;
+import com.codeborne.selenide.WebDriverRunner;
 import org.junit.jupiter.api.BeforeEach;
 import org.junit.jupiter.api.Test;
 import org.openqa.selenium.remote.DesiredCapabilities;
@@ -42,5 +43,6 @@ public class FileDownloadTest {
 
     assertThat(file.getName()).isEqualTo("some-file.txt");
     assertThat(readFileToString(file, UTF_8)).startsWith("{\\rtf");
+    assertThat(WebDriverRunner.getBrowserDownloadsFolder()).isNotNull();
   }
 }

```

Expected behaviour:
When `getBrowserDownloadsFolder` is called, all files available on `http://selenoid:4444/download/<SESSIONID>/?json` should be downloaded do `Configuration.downloadsFolder` and be locally accessible.

**Comment by asolntsev** [comment]
@mszajowskiwr Can you specify why this is a problem?
Yes, `getBrowserDownloadsFolder()` returns null, but why do you need it? 

The idea was that method `$.download()` returns a `File` which is already saved in a right folder. You don't ever need to check any folders.

**Comment by mszajowskiwr** [comment]
Sometimes, we just `.click()` an element, and the file is downloaded. How can we reach it in that case?

I mean to do something like this:
```java
    
    $("a#attachment-file").click();  // browser by default downloads this file on click
    String expectedFilename = "attachment.file";
    File expectedFile = WebDriverRunner.getBrowserDownloadsFolder()
            .files()
            .stream()
            .filter(f -> f.getName().equals(expectedFilename))
            .findFirst()
            .get();
    assertThat(expectedFile).hasContent("expected file content");
```

**Comment by asolntsev** [comment]
@mszajowskiwr exactly! Selenide already does it for you: clicks and waits for the file.

You can just replace your Code by 
```
File file = $("a#attachment-file").download();
```

**Comment by mszajowskiwr** [comment]
Yeah, but the deal is - I need to "click" the link, not "download" it. That's the whole point here...

**Comment by asolntsev** [comment]
@mszajowskiwr why do you need to clicks?

**Comment by mszajowskiwr** [comment]
@asolntsev Because based on the page code, browser config and HTTP headers of given endpoint, the behaviour might be different. 

For example: `<a href="./some_file.html">` - clicking this, will open it as a HTML page, unless the server hosts `./some_file.html` as a `application/zip` - in that case, clicking will result in download.

So - if I `download()` the `<a>` above, it will always be downloaded, but if I `click()` it, it may be either opened as a new page or it may be downloaded - depending on the server situation.

The same case is with the [download links](https://www.w3schools.com/howto/howto_html_download_link.asp).

**Comment by asolntsev** [comment]
@mszajowskiwr Sorry, I don't understand.
If your code looks like your described:
```
$("a#attachment-file").click();  // browser by default downloads this file on click
File expectedFile = findFileIn(WebDriverRunner.getBrowserDownloadsFolder());
```

Then Selenide method `$.download()` does **exactly that**.

**Comment by mszajowskiwr** [comment]
So the only difference between `.click()` and `.download()` is the return value and file handling in the background? Assuming that browser/server **does not** download the file on click, when I use `$("a#some-page").download()` it will navigate to the `some-page`?

This doesn't seem to be true. For example:
```java
open("https://www.learningcontainer.com/sample-zip-files/");
$(".entry-content p a[href='https://en.wikipedia.org/wiki/Zip_(file_format)']").download()
```
The above does not redirect to the wiki ZIP page, if `download()` would've been `click`-ing, we would see a redirect. What am I missing here?

**Comment by asolntsev** [comment]
@mszajowskiwr First of all, do you know that there is 3 ways to download files in Selenide (`HTTPGET`, `PROXY`, `FOLDER`)? 

I am currently talking about `FOLDER` mode. 
It works like this:
1. Click the element
2. During 4 seconds, watch for new files in browser's downloads folder. 
You code in https://github.com/selenide/selenide-selenoid/issues/3#issuecomment-765316676 does exactly that. 

You just can watch into the code: 
1. Selenide `FOLDER` download mode: https://github.com/selenide/selenide/blob/master/src/main/java/com/codeborne/selenide/impl/DownloadFileToFolder.java
2.  The same in `selenide-selenoid`: https://github.com/selenide/selenide-selenoid/blob/main/src/main/java/org/selenide/selenoid/DownloadFileInSelenoid.java

**Comment by mszajowskiwr** [comment]
I've prepared a test that covers what I mean here, please pull [this branch](https://github.com/mszajowskiwr/selenoid-sample/tree/selenoid_download_issue_reproduction), host the `index.html` file locally, tune your `Configuration.baseUrl` and run the `FileDownloadTest`.

To reproduce the issue, please **host** the `index.html` file on your machine (you can simply host it by executing `ruby -run -e httpd . -p 8888` in the directory of the `index.html` file. _(NOTE: when the file is opened locally via `file://`, the expected behavior of `download` attribute is not being honoured by browser, hence we need to host it as a `http://` service)._

The general idea is that the tests should be webdriver-agnostic. In the reproduction above we observe different behaviour based on whether we use native local browser or remote Selenoid-driven one.

The most important thing, is that I need to validate what happens when my customers click on the `this is download` link. If my test would be using `download()` on it, it would always be downloaded, even if the customers would observe navigating to it.

![image](https://user-images.githubusercontent.com/56036647/106180280-64de1300-619c-11eb-89b6-f673a4b0774c.png)

**Comment by asolntsev** [comment]
@mszajowskiwr Thank you for the test, it helped me to understand your concern. 
And thank you for html attribute `download`, I didn't know it! :)

About your concern: 
> If my test would be using download() on it, it would always be downloaded, even if the customers would observe navigating to it.

It's **not true**. You just need to use method `File f = downloadable.download();`. That's it. It will do exactly what you want:
1. Click the link,
2. Wait for a freshly downloaded file inside Selenoid container
3. Copy this file to your local machine `build/downloads/uuid` subfolder.

If the customer would observe navigating to file, then method `downloadable.download()` would also throw an exception. 
Your test `thisAlsoDoesntWork` proves it.

**Comment by mszajowskiwr** [comment]
> If the customer would observe navigating to file, then method `downloadable.download()` would also throw an exception.
Your test `thisAlsoDoesntWork` proves it.

In that case, it seems that native browser behaviour is buggy: `thisAlsoWorks` should fail, because `navigable.download();` over there succeeds and the assertion just below it proves that the page has not been navigated to! 

So, to sum up:
- I expect that when customer clicks a link, it's being downloaded
- I test it via `download()` - my test passes even if customers would observe navigating to. `thisAlsoWorks` proves it.


If my understanding is correct, changing the `disableSelenoid()` to set the `FileDownloadMode.FOLDER` should fix the problem: however in that case, I observe NPE somewhere in `downloadable.download()`

**Comment by asolntsev** [comment]
Hi @mszajowskiwr .
It seems I still don't understand you :(

>  it seems that native browser behaviour becomes buggy with the plugin
1. What plugin do you mean? `selenide-selenoid`? No, browser behaviour cannot depend on any Selenide plugins.
2. And I still think that browser behaviour is correct. 

> `thisAlsoWorks` should fail, because navigable.download(); over there succeeds
In method `thisAlsoWorks` you are using `Configuration.fileDownload = HTTPGET`.
In `HTTPGET` mode, browser does not download files at all. It's Selenide which downloads files. Method `$.download()` ignores any `download` attributes. It just gets `href` attribute and performs "http GET" request with this url. In that sense behaviour of `$.download()` may different from browser's behaviour, yes. This is the definition of `fileDownload = HTTPGET`. 

> changing the disableSelenoid() to set the FileDownloadMode.FOLDER should fix the problem
Yes, it should fix the problem. 

> however in that case, I observe NPE in SelenoidClient.java:39:

Hm... We may consider it as a bug in `selenide-selenoid` plugin. It was not meant to be used with local browser. 
We can easily fix it to support both local and remote browser. I registered a feature request: https://github.com/selenide/selenide-selenoid/issues/4

> How do I NOT use the selenide-selenoid plugin if I'm using native browser webdriver?
1. upgrade to next version of `selenide-selenoid` when `issues 4` is implemented.
2. or try `Configuration.fileDownload = PROXY`.

**Comment by asolntsev** [comment]
@mszajowskiwr Please try to upgrade to `selenide-selenoid:1.0.1`

**Comment by mszajowskiwr** [comment]
@asolntsev that did the trick, thanks!
